/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveillanceRouteImport } from './routes/surveillance'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIdRouteImport } from './routes/archive.$id'

const SurveillanceRoute = SurveillanceRouteImport.update({
  id: '/surveillance',
  path: '/surveillance',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/reports': typeof ReportsRoute
  '/signal': typeof SignalRoute
  '/surveillance': typeof SurveillanceRoute
  '/archive/$id': typeof ArchiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/reports': typeof ReportsRoute
  '/signal': typeof SignalRoute
  '/surveillance': typeof SurveillanceRoute
  '/archive/$id': typeof ArchiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/reports': typeof ReportsRoute
  '/signal': typeof SignalRoute
  '/surveillance': typeof SurveillanceRoute
  '/archive/$id': typeof ArchiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/reports'
    | '/signal'
    | '/surveillance'
    | '/archive/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/reports'
    | '/signal'
    | '/surveillance'
    | '/archive/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/reports'
    | '/signal'
    | '/surveillance'
    | '/archive/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SignalRoute: typeof SignalRoute
  SurveillanceRoute: typeof SurveillanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surveillance': {
      id: '/surveillance'
      path: '/surveillance'
      fullPath: '/surveillance'
      preLoaderRoute: typeof SurveillanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id': {
      id: '/archive/$id'
      path: '/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof ArchiveRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveIdRoute: typeof ArchiveIdRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveIdRoute: ArchiveIdRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SignalRoute: SignalRoute,
  SurveillanceRoute: SurveillanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
